services:
  db:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: dev
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
volumes:
  db_data:
